version: "3.9"

services:
  php-apache:
    ports:
      - "80:80"
    build: './build/php'
    volumes:
      - ./app:/var/www/html
      - ./build/php/datasec.conf:/etc/apache2/sites-available/datasec.conf
      - ./build/php/php.ini:/usr/local/etc/php/php.ini
      - ./logs:/logs
    restart: "on-failure"

  #mysql:
  #  secrets:
  #    - db_root_password
  #    - db_someuser_password
  #  ports:
  #    - "3306:3306"
  #  build: './build/mysql'
  #  environment:
  #    MYSQL_USER: someuser
  #    MYSQL_DATABASE: "datasec_db"
  #    MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
  #    MYSQL_PASSWORD_FILE: /run/secrets/db_someuser_password
  #  volumes:
  #    - dbData:/var/lib/mysql
  mysql:
    secrets:
      - db_root_password
    build: './build/mysql'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    volumes:
      - dbData:/var/lib/mysql
      - ./build/mysql/init:/docker-entrypoint-initdb.d
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: "on-failure"

volumes:
  app:
  dbData:

secrets:
  db_root_password:
    file: db_root_password.txt
  db_someuser_password:
    file: db_someuser_password.txt
